{% set name = "humanleague" %}
{% set version = "2.1.7" %}
{% set sha256 = "1c2107980c8099652ee4cf0b78f35fdb54e73a2e306acb341f1f1fb3ba472f51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py < 34]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - humanleague

about:
  home: https://github.com/virgesmith/humanleague
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsynthesis using quasirandom sampling and/or IPF
  dev_url: https://github.com/virgesmith/humanleague

extra:
  recipe-maintainers:
    - virgesmith
