{% set name = "humanleague" %}
{% set version = "2.2.0" %}
{% set sha256 = "d3a57fef2d23c5bb97208cea1597b1ccb52942bded61c454e60f68ae89492db0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py < 34]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11 >=2.5.0
    - pytest-runner
  run:
    - python
    - numpy

test:
  imports:
    - humanleague

about:
  home: https://github.com/virgesmith/humanleague
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsynthesis using quasirandom sampling and/or IPF
  dev_url: https://github.com/virgesmith/humanleague

extra:
  recipe-maintainers:
    - virgesmith
