appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gpSTybCE51pbxITRBJ8VNotktzdATGjAtUaRajAEGKGJvqSGbSNiXMZ+OOAp+FZCayApJ+2ssO86AED1gpj+1QljcOZ3qLHgg1yl+rgbJr1/FXmmqe65Jd38Hqln20Sm2fD0uLX1RRZKUp3kUFQ0H4Tz1vGN3duVKG4ekIE1fV7eQn64QR7hC4NxaQ7jTECUEcgg4rIwoGVRCudXoCv0GGNucL37QxMKRekMU+y35r6PMglis3EnQtNolv7VGgrI34B2PAe/x8jUjgiuXzCYcNxn653HhNF8W4HaYYkognpZ6UIUi5gkYLzk7JuJVo9E1OdCrbelUf/xYUv5FuE0nW4D12ccY50dbze7Okb7MtAMsMmCdZAMt6iKCy+AZNIJfY/Mrlo1ecAYTSYORRZ9fopu9acirRTJVfLFrHBwutC7AItWCkKix3r31AlJ+i/pyoRZEDoIhx4CT5MGeZbOxLxwaxX8WZzdQtr1+hiBrjNW6a1u1S7wwdt4U76IGeUaZJNvpH+l4L0EyVMQV/mt9CP9tDfId4ryfQudtYMmts1QJgUNkaX0eB9hTnMGdGJOPv7d7yPNTAtq7INTNfxVBUOBCYsFs/Uq5rPbiZIPcR7U/tOV6w8NGrmvnrKsbrbHmIAlz8N7/sb3aTaxerhaW4Nb1/yhSsy8zWtdMXPaH18=}
